name: flutter_shaka
description: A Flutter library that wraps Shaka Player for playing adaptive streaming videos in your Flutter applications.
version: 0.0.1
repository: https://github.com/SairamVemula/flutter_shaka.git

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
